// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Auth0UserID struct {
	Auth0UserID string `json:"Auth0UserID"`
}

type UserInfo struct {
	Email      string `json:"email"`
	FamilyName string `json:"familyName"`
	GivenName  string `json:"givenName"`
}
